name: deploy workflow
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4 #

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v4

      - name: Install Dependencies
        uses: ./.github/actions/cache_dependencies

      - name: Testing Code
        id: test
        run: npm run test
